# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HiddenVarRidgei <- function(ii, tX, aRand, bRand, cSigma, dSigma, maxiter, varSel) {
    .Call('ShrinkNet_HiddenVarRidgei', PACKAGE = 'ShrinkNet', ii, tX, aRand, bRand, cSigma, dSigma, maxiter, varSel)
}

HiddenEdgeBFprime <- function(idx, themat, tX) {
    .Call('ShrinkNet_HiddenEdgeBFprime', PACKAGE = 'ShrinkNet', idx, themat, tX)
}

HiddenEstimatep0 <- function(themat, tX) {
    .Call('ShrinkNet_HiddenEstimatep0', PACKAGE = 'ShrinkNet', themat, tX)
}

HiddenEdgeSelection <- function(themat, tX, p0, lfdrcut, maxNbEdges) {
    .Call('ShrinkNet_HiddenEdgeSelection', PACKAGE = 'ShrinkNet', themat, tX, p0, lfdrcut, maxNbEdges)
}

HiddenVarRidgeiGetKappa <- function(ii, SVDs, tX, aRand, bRand, bRandStarInit, dSigmaStarInit) {
    .Call('ShrinkNet_HiddenVarRidgeiGetKappa', PACKAGE = 'ShrinkNet', ii, SVDs, tX, aRand, bRand, bRandStarInit, dSigmaStarInit)
}

HiddenVarAlgo <- function(SVDs, tX, aRand, bRand, maxiter, globalShrink, tol, verbose) {
    .Call('ShrinkNet_HiddenVarAlgo', PACKAGE = 'ShrinkNet', SVDs, tX, aRand, bRand, maxiter, globalShrink, tol, verbose)
}

getSVD <- function(ii, tX) {
    .Call('ShrinkNet_getSVD', PACKAGE = 'ShrinkNet', ii, tX)
}

