# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HiddenVarRidgei <- function(ii, tX, aRand, bRand, cSigma, dSigma, maxiter, varSel) {
    .Call('ShrinkNet_HiddenVarRidgei', PACKAGE = 'ShrinkNet', ii, tX, aRand, bRand, cSigma, dSigma, maxiter, varSel)
}

HiddenEdgeBFprime <- function(idx, themat, tX) {
    .Call('ShrinkNet_HiddenEdgeBFprime', PACKAGE = 'ShrinkNet', idx, themat, tX)
}

HiddenEstimatep0 <- function(themat, tX) {
    .Call('ShrinkNet_HiddenEstimatep0', PACKAGE = 'ShrinkNet', themat, tX)
<<<<<<< HEAD
}

HiddenEdgeSelection <- function(themat, tX, p0, lfdrcut) {
    .Call('ShrinkNet_HiddenEdgeSelection', PACKAGE = 'ShrinkNet', themat, tX, p0, lfdrcut)
=======
>>>>>>> 1e661989d45a6a528a695a52841e919e34f8c7a5
}

HiddenEdgeSelection <- function(themat, tX, p0, lfdrcut) {
    .Call('ShrinkNet_HiddenEdgeSelection', PACKAGE = 'ShrinkNet', themat, tX, p0, lfdrcut)
}

<<<<<<< HEAD
=======
HiddenVarRidgeiGetKappa <- function(ii, SVDs, aRand, bRand, bRandStarInit, dSigmaStarInit) {
    .Call('ShrinkNet_HiddenVarRidgeiGetKappa', PACKAGE = 'ShrinkNet', ii, SVDs, aRand, bRand, bRandStarInit, dSigmaStarInit)
}

>>>>>>> 1e661989d45a6a528a695a52841e919e34f8c7a5
HiddenVarAlgo <- function(SVDs, aRand, bRand, maxiter, globalShrink, tol, verbose) {
    .Call('ShrinkNet_HiddenVarAlgo', PACKAGE = 'ShrinkNet', SVDs, aRand, bRand, maxiter, globalShrink, tol, verbose)
}

getSVD <- function(ii, tX) {
    .Call('ShrinkNet_getSVD', PACKAGE = 'ShrinkNet', ii, tX)
}

