# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edgeSelection <- function(themat, tX, p0, maxedges, lfdrcut) {
    .Call('ShrinkNet_edgeSelection', PACKAGE = 'ShrinkNet', themat, tX, p0, maxedges, lfdrcut)
}

estimatep0 <- function(themat, tX, maxedges) {
    .Call('ShrinkNet_estimatep0', PACKAGE = 'ShrinkNet', themat, tX, maxedges)
}

mydigamma <- function(vec) {
    .Call('ShrinkNet_mydigamma', PACKAGE = 'ShrinkNet', vec)
}

varAlgo <- function(SVDs, aRand, bRand, maxiter, globalShrink) {
    .Call('ShrinkNet_varAlgo', PACKAGE = 'ShrinkNet', SVDs, aRand, bRand, maxiter, globalShrink)
}

varRidgei <- function(ii, tX, aRand, bRand, cSigma, dSigma, maxiter, varSel) {
    .Call('ShrinkNet_varRidgei', PACKAGE = 'ShrinkNet', ii, tX, aRand, bRand, cSigma, dSigma, maxiter, varSel)
}

varRidgeiOneIter <- function(ii, SVDs, aRand, bRand, bRandStarInit, dSigmaStarInit) {
    .Call('ShrinkNet_varRidgeiOneIter', PACKAGE = 'ShrinkNet', ii, SVDs, aRand, bRand, bRandStarInit, dSigmaStarInit)
}

